<div class="container">
        <div class="footer_inner clearfix">
          <div class="ftr_block_item">
            <div class="ftr_social">
               <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-social')->toHtml();?> 
            </div>
            <div class="ftr_sbscribe">
              <p class="color_gray">Sign Up! </p>
              <p>Get special offers & Giveaways.</p>
              <?php 
                	echo $this->getLayout()->createBlock("Magento\Newsletter\Block\Subscribe")->setTemplate("Magento_Newsletter::subscribe/subscribe.phtml")->toHtml(); 
                ?>
            </div>           
          </div>
           <div class="ftr_block_item">
             <h4>Product</h4>           
              <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-products')->toHtml(); ?> 
           </div>
           <div class="ftr_block_item">
             <h4>Support</h4>
              <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-support')->toHtml();?> 
           </div>
           <div class="ftr_block_item">
             <h4>Company</h4>
              <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-company')->toHtml();?> 
           </div>
           <div class="ftr_block_item">
             <div class="lp_logo_ftr">
               <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-logo')->toHtml();?> 
             </div>
             <div class="ftr_language">
               <ul>
                 <li class="active"><a href="#"> <img src="<?php echo $block->getViewFileUrl('images'); ?>/usa.png" class="img-responsive"> English (USA)</a></li>
                 <li><a href="#"> <img src="<?php echo $block->getViewFileUrl('images'); ?>/spain.png" class="img-responsive"> Español</a></li>
               </ul>
             </div>
             <div class="ssl_log_ftr">
               <img src="<?php echo $block->getViewFileUrl('images'); ?>/ssl_logo.png" class="img-responsive">
             </div>
           </div>
        </div>

        <div class="ftr_bottom">
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-bottom')->toHtml();?> 
          <!-- <ul>
            <li>
              <a href="#">Terms of service</a>
            </li>
            <li>
              <a href="#">Sitemap</a>
            </li>
            <li>
              <a href="privacy_policy.html">Privacy Policy</a>
            </li>
          </ul> -->
        </div>
      </div>