<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<!-- <div class="block newsletter">
    <div class="title"><strong>Newsletter</strong></div>
    <div class="content"> -->
        <form class="newsletter_formftr"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
           <!--  <div class="field newsletter">
                <label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ //echo __('Sign Up for Our Newsletter:') ?></span></label>
                <div class="control"> -->
                    <input name="email" type="email" class="form-control" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Email Address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
              <!--   </div>
            </div> -->
           <!--  <div class="actions"> -->
                <button class="" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <?php /* @escapeNotVerified */ echo __('Subscribe Now') ?>
                </button>
            <!-- </div> -->
        </form>
<!--     </div>
</div>
 -->